DROP TABLE playerTable CASCADE CONSTRAINTS;
DROP TABLE loginTable CASCADE CONSTRAINTS;
DROP TABLE loginHistory CASCADE CONSTRAINTS;
DROP TABLE gameSessions CASCADE CONSTRAINTS;
DROP TABLE achievements CASCADE CONSTRAINTS;
--Create table playerTable
CREATE TABLE playerTable
(
    player_id   CHAR(10)    PRIMARY KEY,
    gamertag    VARCHAR(20) NOT NULL,
    first_name  VARCHAR(20) NOT NULL,
    last_name   VARCHAR(30) NOT NULL
);

--Create table loginTable
CREATE TABLE loginTable
(
    login_id    NUMBER      PRIMARY KEY,
    player_id   CHAR(10)    UNIQUE NOT NULL, 
    email       VARCHAR(50) UNIQUE NOT NULL,
    passwrd      VARCHAR(255)UNIQUE NOT NULL,
    FOREIGN KEY (player_id) REFERENCES playerTable(player_id)
);

--Create table loginHistory
CREATE TABLE loginHistory
(
    login_id        NUMBER,
    player_id       CHAR(10) NOT NULL,
    login_timestamp TIMESTAMP,
    FOREIGN KEY (login_id) REFERENCES loginTable(login_id),
    FOREIGN KEY (player_id) REFERENCES playerTable(player_id)
);

--Create table gameSessions
CREATE TABLE gameSessions (
    session_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id CHAR(10)  NOT NULL,
    session_start       TIMESTAMP,
    session_end         TIMESTAMP,
    total_playtime            NUMBER,
    FOREIGN KEY (player_id) REFERENCES playerTable(player_id)
);

CREATE TABLE achievements 
(
    player_id           CHAR(10),
    achievements        achievement_list,
    achievement_date    DATE,
    FOREIGN KEY(player_id) REFERENCES playerTable(player_id)
) NESTED TABLE achievements STORE AS achievement_store;
    
    
    